#ifndef PACKET_H
#define PACKET_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Maximum payload size suppported by SerialStack 
 */
#define SS_MAX_PAYLOAD_SIZE 64

/**
 * @brief SerialStack packet representation
 * 
 * This structure represents a logical SerialStack packet
 * Framing fields such as SOF, CRC8, and EOF are not stored
 * here because they are generated by  the codec layer.
 */
typedef struct
{
    uint8_t version;
    uint8_t destination;
    uint8_t source;
    uint8_t command;
    uint8_t sequence;
    uint8_t length;
    uint8_t payload[SS_MAX_PAYLOAD_SIZE];
} ss_packet_t;

/**
 * @brief Initializes a packet structure.
 * 
 * All fields are cleared to zero.
 * 
 * @param packet Packet to initialize. 
 */
void packet_init(ss_packet_t *packet);

/**
 * @brief clears packet contents
 * 
 * @param packet packet to clear.*/
void packet_clear(ss_packet_t *packet);

/**
 * @brief copies one packet to another.
 * 
 * @param desination Destination packet.
 * @param source Source packet.
 */
void packet_copy(ss_packet_t *destination, 
                const ss_packet_t *source);

#ifdef __cplusplus
}
#endif

#endif /* PACKET_H */







